export enum FetchGameAction {
    FETCH_GAME = 'FETCH_GAME',
    FETCH_GAME_SUCCESS = 'FETCH_GAME_SUCCESS',
    FETCH_GAMES = 'FETCH_GAMES',
    FETCH_GAMES_SUCCESS = 'FETCH_GAMES_SUCCESS'
}

export type SET_EDIT_MODE = 'SET_EDIT_MODE';
export const SET_EDIT_MODE: SET_EDIT_MODE = 'SET_EDIT_MODE';

export enum GameEdit {
    GAME_EDIT_NAME = 'GAME_EDIT_NAME',
    GAME_EDIT_NAME_SUCCESS = 'GAME_EDIT_NAME_SUCCESS',
    GAME_EDIT_MIN_PLAYERS = 'GAME_EDIT_MIN_PLAYERS',
    GAME_EDIT_MIN_PLAYERS_SUCCESS = 'GAME_EDIT_MIN_PLAYERS_SUCCESS',
    GAME_EDIT_MAX_PLAYERS = 'GAME_EDIT_MAX_PLAYERS',
    GAME_EDIT_MAX_PLAYERS_SUCCESS = 'GAME_EDIT_MAX_PLAYERS_SUCCESS',
    GAME_EDIT_BOX_ART = 'GAME_EDIT_BOX_ART',
    GAME_EDIT_BOX_ART_SUCCESS = 'GAME_EDIT_BOX_ART_SUCCESS',
    GAME_EDIT_BBG_LINK = 'GAME_EDIT_BBG_LINK',
    GAME_EDIT_BBG_LINK_SUCCESS = 'GAME_EDIT_BBG_LINK_SUCCESS'
}

// const SERVICE_IDENTIFIER = {
//     DB: Symbol("Database")
// };

// export default SERVICE_IDENTIFIER;

